// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cmoutafidis

//@version=5
indicator(title="Hello world")

atr = ta.atr(14)
plot(atr)

atrPoints = atr / syminfo.mintick
plot(atrPoints, color = color.red)

atrPips = atrPoints / 10
plot(atrPips, color = color.purple)

if barstate.islast
    label.new(bar_index, high, text = syminfo.description)
    label.new(bar_index, low, text = syminfo.tickerid, color = color.red)
