// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cmoutafidis

//@version=5
indicator(title="Fractal enculfing Caldles", overlay = true)

pointAllowance = input.int(defval = 0)
swingHigh = high == ta.highest(high, 10) or high[1] == ta.highest(high, 10)
swingLow = low == ta.lowest(low, 10) or low[1] == ta.lowest(low, 10)

// previus bar is bearish, the current bar opened lower than prev close, current bar closed higher than prev open, and swing low/high
var allowance = syminfo.mintick * pointAllowance
bullEc = close[1] < open[1] and open <= (close[1] + pointAllowance) and close >= open[1] and swingLow
bearEc = close[1] > open[1] and open >= (close[1] - pointAllowance) and close <= open[1] and swingHigh

plotshape(bullEc, style = shape.triangleup, location = location.belowbar, color = color.green, size = size.small)
plotshape(bearEc, style = shape.triangledown, location = location.abovebar, color = color.red, size = size.small)